### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GrosSacASac** [miguelmota/handyman#1]
What is the main difference between miguelmota/handyman and padolsey/operative ?

**Comment by miguelmota** [comment]
@GrosSacASac I think at the time it was simply just adding [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) support. However right now this lib is deprecated and you should jus use [operative](https://github.com/padolsey/operative).
